issuer: http://127.0.0.1:5556
storage:
  type: sqlite3
  config:
    file: examples/dex.db
listen: http://0.0.0.0:5555

web:
  http: 0.0.0.0:5556
  # Uncomment for HTTPS options.
  # https: 127.0.0.1:5554
  # tlsCert: /etc/dex/tls.crt
  # tlsKey: /etc/dex/tls.ke

expiry:
  signingKeys: "10m"
  idTokens: "30m"

logger:
  level: "debug"
  format: "json"

oauth2:
  responseTypes: ["code", "token", "id_token"]
  skipApprovalScreen: true

connectors:
- type: mockCallback
  id: mock
  name: Example

staticClients:
- id: example-cluster-client-id
  name: Kubernetes Dev Cluster
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0
  redirectURIs:
    - http://127.0.0.1:5555/callback/example-cluster
    - http://127.0.0.1:5555/callback/redirect-to-k8s-dashboard 
    - http://127.0.0.1:5555/callback/example-cluster-three

enablePasswordDB: True

staticPasswords:
- email: "admin@example.com"
  # bcrypt hash of the string "password"
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

clusters:
  - name: dev-test
    short_description: "Dev Test"
    description: "Development Dummy Dex"
    redirect_uri: 'http://127.0.0.1:5555/callback'
    client_secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    client_id: example-app
    issuer: http://127.0.0.1:5556/dex
    k8s_master_uri: https://dummy-k8s.example.com:6443
    static_context_name: false
    k8s_ca_pem: |
      -----BEGIN CERTIFICATE-----
      MIICyDCCAbCgAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
      cm5ldGVzMB4XDTE5MDYxMjIwMjI1M1oXDTI5MDYwOTIwMjI1M1owFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALgb
      n32KzvzxyiAENMjz3eR5dxpqVzGwUg2o4b2ztslEOtaPHIMdc91czk0ceeG5X60P
      zk3eZV5Ab0dmg7g1D+4DVyMCfnflqG0zZ5J1I5ZhzeWPVU4dPdxQxAlS4dN4Dadc
      2KaQmTTeSSkSkRkb1OuewXO4XcoLyrzsyI4aoas8cIcuZwweFCgE1Byvlbt990Ey
      +wnqDqaAmrwg2IV6nCMjEg2M4YuGzBtPwK40G4gdcWr5gQfi7hny5PpNG779S2DU
      L9M8UQAfn0olx2qJrjfLGHbPgNYH85Em0QeFTI6SS/R0pk+6YujSaHIYw80jcOYw
      b/TYZ6u3BeQvhrJcGOsCAwEAAaMjMCEwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB
      /wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBABJbpscmucuQyJdZGa+Q5PVU0EnO
      18Tmu74Q01viOj185BcnyYElHX9eNfXEndV02qAeRu8H+H5EICc4DnA4ZUiWxwPE
      XiwFeDFZslKRTKP831ccAgYDDA+x6mNPqwxyi2OitqZmhP/8d+2df0USF0NzEzhv
      SUINoAjLDmv9Vvmvi/9fKz0hrEK5754EYLI7ixjQjzx2vhNt+7ZnXKHPEKYoc9bj
      KOO6NwonzNknjDcp0b/y6Dvg1VTf4mhF7OSCZPN0ZKqD/XElDyE17xPY0uJL8sEZ
      CaMMHlH4V9UFWglw7aT30UoSQCZ3hosoL43CIx4VFCkztoQLokCDvFqIth4=
      -----END CERTIFICATE-----
trusted_root_ca: |-2
  -----BEGIN CERTIFICATE-----
  MIICyDCCAbCgAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
  cm5ldGVzMB4XDTE5MDYxMjIwMjI1M1oXDTI5MDYwOTIwMjI1M1owFTETMBEGA1UE
  AxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALgb
  n32KzvzxyiAENMjz3eR5dxpqVzGwUg2o4b2ztslEOtaPHIMdc91czk0ceeG5X60P
  zk3eZV5Ab0dmg7g1D+4DVyMCfnflqG0zZ5J1I5ZhzeWPVU4dPdxQxAlS4dN4Dadc
  2KaQmTTeSSkSkRkb1OuewXO4XcoLyrzsyI4aoas8cIcuZwweFCgE1Byvlbt990Ey
  +wnqDqaAmrwg2IV6nCMjEg2M4YuGzBtPwK40G4gdcWr5gQfi7hny5PpNG779S2DU
  L9M8UQAfn0olx2qJrjfLGHbPgNYH85Em0QeFTI6SS/R0pk+6YujSaHIYw80jcOYw
  b/TYZ6u3BeQvhrJcGOsCAwEAAaMjMCEwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB
  /wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBABJbpscmucuQyJdZGa+Q5PVU0EnO
  18Tmu74Q01viOj185BcnyYElHX9eNfXEndV02qAeRu8H+H5EICc4DnA4ZUiWxwPE
  XiwFeDFZslKRTKP831ccAgYDDA+x6mNPqwxyi2OitqZmhP/8d+2df0USF0NzEzhv
  SUINoAjLDmv9Vvmvi/9fKz0hrEK5754EYLI7ixjQjzx2vhNt+7ZnXKHPEKYoc9bj
  KOO6NwonzNknjDcp0b/y6Dvg1VTf4mhF7OSCZPN0ZKqD/XElDyE17xPY0uJL8sEZ
  CaMMHlH4V9UFWglw7aT30UoSQCZ3hosoL43CIx4VFCkztoQLokCDvFqIth4=
  -----END CERTIFICATE-----
